config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'docs#index'
  resources :docs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  TYPES = %w{ new fix update }

  after_initialize :set_defaults

  validates :announcement_type, :description, :name, :published_at, presence: true
  validates :announcement_type, inclusion: { in: TYPES }

  def set_defaults
    self.published_at      ||= Time.zone.now
    self.announcement_type ||= TYPES.first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  Devise.omniauth_configs.keys.each do |provider|
    scope provider, ->{ where(provider: provider) }
  end

  def client
    send("#{provider}_client")
  end

  def expired?
    expires_at? && expires_at <= Time.zone.now
  end

  def access_token
    send("#{provider}_refresh_token!", super) if expired?
    super
  end


  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_app_id
      config.consumer_secret     = Rails.application.secrets.twitter_app_secret
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def twitter_refresh_token!(token); end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :masqueradable, :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  has_one_attached :avatar
  has_person_name

  has_many :notifications, as: :recipient
  has_many :services
  has_many :docs
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :mark_as_read, if: :user_signed_in?

  def index
    @announcements = Announcement.order(published_at: :desc)
  end

  private

    def mark_as_read
      current_user.update(announcements_last_read_at: Time.zone.now)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :masquerade_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
    end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
before_action :find_doc, only: [:show, :edit, :update, :destroy]
def index
  @docs = Doc.where(user_id: current_user).order("created_at DESC")
end
def show
  @doc = Doc.find(params[:id])
end

def new
  @doc = current_user.docs.build
end
def create
  @doc = current_user.docs.build(doc_params)
  if @doc.save
    redirect_to @doc
  else
    render :action => 'new'
  end
end
def edit
  @doc = Doc.find(params[:id])
end
def update
   if @doc.update(doc_params) 
    redirect_to @doc
  else
    render 'edit'
   end
end
def destroy
  Doc.find(params[:id]).destroy
  #redirect_to @docs_path
  redirect_to :action => 'list'
end

private
def find_doc
  @doc = Doc.find(params[:id])
end
def doc_params
   params.require(:doc).permit(:title,:content)
  
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    # Convert the database records to Noticed notification instances so we can use helper methods
    @notifications = current_user.notifications.map(&:to_notification)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_action :set_service
    before_action :set_user

    attr_reader :service, :user

    def facebook
      handle_auth "Facebook"
    end

    def twitter
      handle_auth "Twitter"
    end

    def github
      handle_auth "Github"
    end

    private

    def handle_auth(kind)
      if service.present?
        service.update(service_attrs)
      else
        user.services.create(service_attrs)
      end

      if user_signed_in?
        flash[:notice] = "Your #{kind} account was connected."
        redirect_to edit_user_registration_path
      else
        sign_in_and_redirect user, event: :authentication
        set_flash_message :notice, :success, kind: kind
      end
    end

    def auth
      request.env['omniauth.auth']
    end

    def set_service
      @service = Service.where(provider: auth.provider, uid: auth.uid).first
    end

    def set_user
      if user_signed_in?
        @user = current_user
      elsif service.present?
        @user = service.user
      elsif User.where(email: auth.info.email).any?
        # 5. User is logged out and they login to a new account which doesn't match their old one
        flash[:alert] = "An account with this email already exists. Please sign in with that account before connecting your #{auth.provider.titleize} account."
        redirect_to new_user_session_path
      else
        @user = create_user
      end
    end

    def service_attrs
      expires_at = auth.credentials.expires_at.present? ? Time.at(auth.credentials.expires_at) : nil
      {
          provider: auth.provider,
          uid: auth.uid,
          expires_at: expires_at,
          access_token: auth.credentials.token,
          access_token_secret: auth.credentials.secret,
      }
    end

    def create_user
      User.create(
        email: auth.info.email,
        #name: auth.info.name,
        password: Devise.friendly_token[0,20]
      )
    end

  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def unread_announcements(user)
    last_announcement = Announcement.order(published_at: :desc).first
    return if last_announcement.nil?

    # Highlight announcements for anyone not logged in, cuz tempting
    if user.nil? || user.announcements_last_read_at.nil? || user.announcements_last_read_at < last_announcement.published_at
      "unread-announcements"
    end
  end

  def announcement_class(type)
    {
      "new" => "text-success",
      "update" => "text-warning",
      "fix" => "text-danger",
    }.fetch(type, "text-success")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_path(object, options = {})
    size = options[:size] || 180
    default_image = options[:default] || "mp"
    base_url =  "https://secure.gravatar.com/avatar"
    base_url_params = "?s=#{size}&d=#{default_image}"

    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size, { gravity: 'Center' }])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
      "#{base_url}/#{gravatar_id}#{base_url_params}"
    else
      "#{base_url}/00000000000000000000000000000000#{base_url_params}"
    end
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-primary"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/announcements/index.html.erb
<h1>What's New</h1>

<div class="card">
  <div class="card-body">
    <% @announcements.each_with_index do |announcement, index| %>
      <% if index != 0 %>
        <div class="row"><div class="col"><hr /></div></div>
      <% end %>

      <div class="row announcement" id="<%= dom_id(announcement) %>">
        <div class="col-sm-1 text-center">
          <%= link_to announcements_path(anchor: dom_id(announcement)) do %>
            <strong><%= announcement.published_at.strftime("%b %d") %></strong>
          <% end %>
        </div>
        <div class="col">
          <strong class="<%= announcement_class(announcement.announcement_type) %>"><%= announcement.announcement_type.titleize %>:</strong>
          <strong><%= announcement.name %></strong>
          <%= simple_format announcement.description %>
        </div>
      </div>
    <% end %>

    <% if @announcements.empty? %>
      <div>Exciting stuff coming very soon!</div>
    <% end %>
  </div>
</div>

app/views/docs/_form.html.erb
<div class="row">
<div class="col-md-6">
<div class="mb-3">
<%= f.text_field :title, label: 'Title', placeholder: "Title" %>
</div>
<div class="mb-3">
<%= f.text_field :content, label: 'Content', placeholder: "Content" %>
</div>
<div class="mb-3">
<%= f.submit "Create New Doc", class: "btn btn-warning mt-2" %>
</div>
</div>
</div>

app/views/docs/edit.html.erb
<h1>Fix: <%= @doc.title %></h1>
<p>
   <strong>Created Date:</strong> <%= @doc.created_at %><br />
</p>
<p><%= @doc.content %></p>


<%= link_to "All Docs", docs_path, class: "btn btn-success btn-sm" %>
<%= link_to "Cancel", doc_path(@doc), class: "btn btn-warning btn-sm" %>
<%= link_to "Trash", doc_path(@doc), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "Are You Sure?" } %>

app/views/docs/index.html.erb
 <div class="row">
<div class="col-md-6">
<div class="mb-3">
 <% @docs.each do |doc|%>
<h2><%= link_to doc.title, doc %></h2>
<p><%= time_ago_in_words(doc.created_at) %></p>
<p><%= truncate(doc.content, length: 50) %>
<% end %>
</div>
</div>
</div>
<%= link_to "Create Doc", new_doc_path, class: "btn btn-warning btn-lg mt-2" %>

app/views/docs/new.html.erb
<h1>New Doc</h1>
<%= form_for(@doc, url: docs_path(@doc)) do |f| %>
<%= render partial: "form", locals: {:f => f} %>
<% end %>

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>
<p>
   <strong>Created Date:</strong> <%= @doc.created_at %><br />
</p>
<p><%= @doc.content %></p>

<%= link_to "All Docs", docs_path, class: "btn btn-success btn-sm" %>
<%= link_to "Fix Doc", edit_doc_path(@doc), class: "btn btn-info btn-sm" %>
<%= link_to "Trash", doc_path(@doc), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "Are You Sure?" } %>

app/views/home/index.html.erb
<h1> Welcome to Filing Cabinet!</h1>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>

    <div class="container mx-auto">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/notifications/index.html.erb
<h1>Notifications</h1>

<ul>
  <% @notifications.each do |notification| %>
    <%# Customize your notification format here. We typically recommend a `message` and `url` method on the Notification classes. %>
    <%#= link_to notification.message, notification.url %>

    <li><%= notification.params %></li>
  <% end %>
</ul>

app/views/shared/_footer.html.erb
 <footer class="text-center text-white mt-4" style="background-color: #8e478e;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register on FileCabinet for free</span>
           <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-outline-light btn-rounded" %>
         
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://xhostcom.com/">FileCabinet</a>
    </div>
    <!-- Copyright -->
  </footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-dark bg-dark" style="background-color:#8e478e!important;">
  <div class="container mx-auto">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
         <li class="nav-item mx-1"><%= link_to "All Docs", docs_path, class: "btn btn-success nav-link" %></li>
         <li class="nav-item mx-1"><%= link_to "New Doc", new_doc_path, class: "btn btn-warning nav-link" %></li>
        <li class="nav-item mx-1"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to notifications_path, class: "nav-link" do %>
            <span><i class="far fa-bell" aria-hidden="true"></i></span>
          <% end %>
         </li>

          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:madmin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<div class="container mx-auto">
  <% flash.each do |msg_type, message| %>
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>